#!/usr/bin/env node
// Build script for the standalone prettier-plugin-bac package.
//
// The formatter implementation lives in the sibling `vscode-bac` repo
// (`../vscode-bac/lsp/src/format/`) so the LSP can reuse the same code
// without a runtime npm dep on the plugin. To publish a standalone Prettier
// plugin we need a self-contained dist/ directory with everything required
// at runtime — no `..` imports.
//
// We solve this by:
//   1. Compiling the LSP TypeScript (`npm run build` in ../vscode-bac/lsp).
//   2. Copying the compiled `script/` (lexer + parser + AST + diagnostics)
//      and `format/` (parser-adapter + printer + format API) folders into
//      our dist/.
//   3. Writing a tiny dist/index.js that re-exports `bacPrettierPlugin`.
//
// The result is a publishable npm package whose only external dep is
// `prettier` (peer-installed by the consumer).
//
// Override the source location with `BAC_VSCODE_REPO=<path>` if you've
// cloned vscode-bac somewhere other than the default sibling location.

const fs   = require('node:fs');
const path = require('node:path');
const cp   = require('node:child_process');

const ROOT     = path.resolve(__dirname, '..');
const LSP_ROOT = process.env.BAC_VSCODE_REPO
  ? path.resolve(process.env.BAC_VSCODE_REPO, 'lsp')
  : path.resolve(ROOT, '..', 'vscode-bac', 'lsp');
const DIST     = path.join(ROOT, 'dist');

if (!fs.existsSync(LSP_ROOT)) {
  console.error(
    `[prettier-plugin-bac] cannot find vscode-bac LSP at ${LSP_ROOT}.\n` +
    `Clone https://github.com/A7E7/vscode-bac next to this repo, or set ` +
    `BAC_VSCODE_REPO=/path/to/vscode-bac and re-run.`,
  );
  process.exit(2);
}

function rm(p)   { fs.rmSync(p, { recursive: true, force: true }); }
function mkdir(p){ fs.mkdirSync(p, { recursive: true }); }
function copy(src, dst) {
  mkdir(path.dirname(dst));
  if (fs.statSync(src).isDirectory()) {
    fs.cpSync(src, dst, { recursive: true });
  } else {
    fs.copyFileSync(src, dst);
  }
}

console.log('[prettier-plugin-bac] building LSP first…');
cp.execSync('npm run build', { cwd: LSP_ROOT, stdio: 'inherit' });

console.log('[prettier-plugin-bac] preparing dist/');
rm(DIST);
mkdir(DIST);

// Copy compiled JS that the formatter depends on. We DON'T copy the
// validator/navigation/completion modules — formatting only needs script + format.
copy(path.join(LSP_ROOT, 'out', 'script'), path.join(DIST, 'script'));
copy(path.join(LSP_ROOT, 'out', 'format'), path.join(DIST, 'format'));

// Tiny entrypoint that re-exports the plugin object.
const indexJs = `// Auto-generated by scripts/build.js — do not edit.
'use strict';
const { bacPrettierPlugin, formatBacText } = require('./format/format');
module.exports = bacPrettierPlugin;
module.exports.default = bacPrettierPlugin;
module.exports.formatBacText = formatBacText;
`;
fs.writeFileSync(path.join(DIST, 'index.js'), indexJs);

const indexDts = `// Auto-generated by scripts/build.js — do not edit.
import type { Plugin } from 'prettier';
declare const bacPrettierPlugin: Plugin;
export = bacPrettierPlugin;
export default bacPrettierPlugin;
export function formatBacText(source: string, options?: { printWidth?: number; tabWidth?: number }): string;
`;
fs.writeFileSync(path.join(DIST, 'index.d.ts'), indexDts);

// Drop a LICENSE next to the package contents so the published tarball
// includes it.
const repoLicense = path.resolve(ROOT, '..', 'LICENSE');
if (fs.existsSync(repoLicense)) {
  copy(repoLicense, path.join(ROOT, 'LICENSE'));
}

console.log('[prettier-plugin-bac] done →', DIST);
